# -*- coding: utf-8 -*-
"""Statystyka4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14j7SEVfPod0BQPKah75hkMgHdka_bXJm
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

"""Wygeneruj próbę losową dla rozkładu normalnego dla średniej = 2, odchylenia = 30 i liczby elementów = 200.
Zbadaj hipotezę mówiącą o tym, że średnia tego rozkładu jest równa 2,5.
"""

normalVar = sps.norm.rvs(loc=1, scale=20, size=1000)
results = sps.ttest_1samp(normalVar,2.5)
print(results)

"""2. Wczytaj plik napoje.csv do pandas DataFrame. Zweryfikuj hipotezę że średnie spożycie piwa lech wynosi
60500, coli wynosi 222000, piw regionalne wynosi 43500.
"""

import scipy.stats as sps

napoje_po_reklamie = pd.read_csv("napoje_po_reklamie.csv" , sep=';')
napoje = pandas.read_csv('napoje.csv', sep=';', na_values='.')

print("Cola: ")
results = sps.ttest_1samp(napoje['cola'],222000)
print(results)

print("lech: ")
results = sps.ttest_1samp(napoje['lech'],60500)
print(results)

print("Regionalne: ")
results = sps.ttest_1samp(napoje['regionalne'],43500)
print(results)

"""3.Sprawdzić która zmienna w pliku napoje.csv wykazuje normalność"""

import scipy.stats as sps
import pandas

napoje = pandas.read_csv('napoje.csv', sep=';', na_values='.')

for x in napoje:
  test = sps.normaltest(napoje[x])
  print(test)

napoje.head()

"""4. Zbadaj równość średnich dla następujących par: okocim – lech, fanta – regionalne oraz cola – pepsi."""

results = sps.ttest_rel(napoje['fanta '] , napoje['regionalne'])
results2 = sps.ttest_rel(napoje['cola'] , napoje['pepsi'])
results3 = sps.ttest_rel(napoje['okocim'] , napoje['lech'])
print(results)
print(results2)
print(results3)

"""5. Zbadaj równość wariancji pomiędzy okocim – lech, żywiec – fanta oraz regionalne – cola."""

levene_test_results = sps.levene(napoje['okocim'] , napoje['lech'])
levene_test_results = sps.levene(napoje['żywiec'] , napoje['fanta '])
levene_test_results = sps.levene(napoje['regionalne'] , napoje['cola'])
print(levene_test_results)

"""6. Zbadaj równość średnich pomiędzy latami 2001 i 2015 dla piw regionalnych."""

is_2001 = napoje['rok']==2001
is_2015 = napoje['rok']==2015
napoje_2001 = napoje[is_2001]
napoje_2015 = napoje[is_2015]
print(napoje_2001.head(3))
print(napoje_2015.head(3))

results = sps.ttest_rel(napoje_2001['regionalne'] , napoje_2015['regionalne'])
print("\n")
print(results)

"""Zbadaj równość średnich dla wartości z roku 2016 oraz dla wartości z pliku napoje_po_reklamie.csv
oddzielnie dla coli, fanty i pepsi. Zakładamy, że zmienne te są zależne.
"""

is_2016 = napoje['rok']==2016
napoje_2016 = napoje[is_2016]

napoje_po_reklamie = pd.read_csv("napoje_po_reklamie.csv" , sep=';')

results = sps.ttest_rel(napoje_po_reklamie['cola'] , napoje_2016['cola'])
print("Cola:")
print(results)
results = sps.ttest_rel(napoje_po_reklamie['fanta '] , napoje_2016['fanta '])
print("Fanta:")
print(results)
results = sps.ttest_rel(napoje_po_reklamie['pepsi'] , napoje_2016['pepsi'])
print("Pepsi:")
print(results)